*---------------------------------------------------------------------*
*    view related data declarations
*   generation date: 04.01.2006 at 11:46:05 by user CHANDRASEKAA
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: CVIV_CCID_LINK..................................*
TABLES: CVIV_CCID_LINK, *CVIV_CCID_LINK. "view work areas
CONTROLS: TCTRL_CVIV_CCID_LINK
TYPE TABLEVIEW USING SCREEN '0011'.
DATA: BEGIN OF STATUS_CVIV_CCID_LINK. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_CVIV_CCID_LINK.
* Table for entries selected to show on screen
DATA: BEGIN OF CVIV_CCID_LINK_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE CVIV_CCID_LINK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_CCID_LINK_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF CVIV_CCID_LINK_TOTAL OCCURS 0010.
INCLUDE STRUCTURE CVIV_CCID_LINK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_CCID_LINK_TOTAL.

*...processing: CVIV_CP1_LINK...................................*
TABLES: CVIV_CP1_LINK, *CVIV_CP1_LINK. "view work areas
CONTROLS: TCTRL_CVIV_CP1_LINK
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_CVIV_CP1_LINK. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_CVIV_CP1_LINK.
* Table for entries selected to show on screen
DATA: BEGIN OF CVIV_CP1_LINK_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE CVIV_CP1_LINK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_CP1_LINK_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF CVIV_CP1_LINK_TOTAL OCCURS 0010.
INCLUDE STRUCTURE CVIV_CP1_LINK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_CP1_LINK_TOTAL.

*...processing: CVIV_CP2_LINK...................................*
TABLES: CVIV_CP2_LINK, *CVIV_CP2_LINK. "view work areas
CONTROLS: TCTRL_CVIV_CP2_LINK
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_CVIV_CP2_LINK. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_CVIV_CP2_LINK.
* Table for entries selected to show on screen
DATA: BEGIN OF CVIV_CP2_LINK_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE CVIV_CP2_LINK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_CP2_LINK_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF CVIV_CP2_LINK_TOTAL OCCURS 0010.
INCLUDE STRUCTURE CVIV_CP2_LINK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_CP2_LINK_TOTAL.

*...processing: CVIV_CP3_LINK...................................*
TABLES: CVIV_CP3_LINK, *CVIV_CP3_LINK. "view work areas
CONTROLS: TCTRL_CVIV_CP3_LINK
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_CVIV_CP3_LINK. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_CVIV_CP3_LINK.
* Table for entries selected to show on screen
DATA: BEGIN OF CVIV_CP3_LINK_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE CVIV_CP3_LINK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_CP3_LINK_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF CVIV_CP3_LINK_TOTAL OCCURS 0010.
INCLUDE STRUCTURE CVIV_CP3_LINK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_CP3_LINK_TOTAL.

*...processing: CVIV_CP4_LINK...................................*
TABLES: CVIV_CP4_LINK, *CVIV_CP4_LINK. "view work areas
CONTROLS: TCTRL_CVIV_CP4_LINK
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_CVIV_CP4_LINK. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_CVIV_CP4_LINK.
* Table for entries selected to show on screen
DATA: BEGIN OF CVIV_CP4_LINK_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE CVIV_CP4_LINK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_CP4_LINK_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF CVIV_CP4_LINK_TOTAL OCCURS 0010.
INCLUDE STRUCTURE CVIV_CP4_LINK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_CP4_LINK_TOTAL.

*...processing: CVIV_CUST_TO_BP1................................*
TABLES: CVIV_CUST_TO_BP1, *CVIV_CUST_TO_BP1. "view work areas
CONTROLS: TCTRL_CVIV_CUST_TO_BP1
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_CVIV_CUST_TO_BP1. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_CVIV_CUST_TO_BP1.
* Table for entries selected to show on screen
DATA: BEGIN OF CVIV_CUST_TO_BP1_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE CVIV_CUST_TO_BP1.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_CUST_TO_BP1_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF CVIV_CUST_TO_BP1_TOTAL OCCURS 0010.
INCLUDE STRUCTURE CVIV_CUST_TO_BP1.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_CUST_TO_BP1_TOTAL.

*...processing: CVIV_CUST_TO_BP2................................*
TABLES: CVIV_CUST_TO_BP2, *CVIV_CUST_TO_BP2. "view work areas
CONTROLS: TCTRL_CVIV_CUST_TO_BP2
TYPE TABLEVIEW USING SCREEN '0008'.
DATA: BEGIN OF STATUS_CVIV_CUST_TO_BP2. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_CVIV_CUST_TO_BP2.
* Table for entries selected to show on screen
DATA: BEGIN OF CVIV_CUST_TO_BP2_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE CVIV_CUST_TO_BP2.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_CUST_TO_BP2_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF CVIV_CUST_TO_BP2_TOTAL OCCURS 0010.
INCLUDE STRUCTURE CVIV_CUST_TO_BP2.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_CUST_TO_BP2_TOTAL.

*...processing: CVIV_LEGFORM_LNK................................*
TABLES: CVIV_LEGFORM_LNK, *CVIV_LEGFORM_LNK. "view work areas
CONTROLS: TCTRL_CVIV_LEGFORM_LNK
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_CVIV_LEGFORM_LNK. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_CVIV_LEGFORM_LNK.
* Table for entries selected to show on screen
DATA: BEGIN OF CVIV_LEGFORM_LNK_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE CVIV_LEGFORM_LNK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_LEGFORM_LNK_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF CVIV_LEGFORM_LNK_TOTAL OCCURS 0010.
INCLUDE STRUCTURE CVIV_LEGFORM_LNK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_LEGFORM_LNK_TOTAL.

*...processing: CVIV_MAP_CONTACT................................*
TABLES: CVIV_MAP_CONTACT, *CVIV_MAP_CONTACT. "view work areas
CONTROLS: TCTRL_CVIV_MAP_CONTACT
TYPE TABLEVIEW USING SCREEN '0012'.
DATA: BEGIN OF STATUS_CVIV_MAP_CONTACT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_CVIV_MAP_CONTACT.
* Table for entries selected to show on screen
DATA: BEGIN OF CVIV_MAP_CONTACT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE CVIV_MAP_CONTACT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_MAP_CONTACT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF CVIV_MAP_CONTACT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE CVIV_MAP_CONTACT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_MAP_CONTACT_TOTAL.

*...processing: CVIV_MARST_LINK.................................*
TABLES: CVIV_MARST_LINK, *CVIV_MARST_LINK. "view work areas
CONTROLS: TCTRL_CVIV_MARST_LINK
TYPE TABLEVIEW USING SCREEN '0006'.
DATA: BEGIN OF STATUS_CVIV_MARST_LINK. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_CVIV_MARST_LINK.
* Table for entries selected to show on screen
DATA: BEGIN OF CVIV_MARST_LINK_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE CVIV_MARST_LINK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_MARST_LINK_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF CVIV_MARST_LINK_TOTAL OCCURS 0010.
INCLUDE STRUCTURE CVIV_MARST_LINK.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_MARST_LINK_TOTAL.

*...processing: CVIV_VEND_TO_BP1................................*
TABLES: CVIV_VEND_TO_BP1, *CVIV_VEND_TO_BP1. "view work areas
CONTROLS: TCTRL_CVIV_VEND_TO_BP1
TYPE TABLEVIEW USING SCREEN '0009'.
DATA: BEGIN OF STATUS_CVIV_VEND_TO_BP1. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_CVIV_VEND_TO_BP1.
* Table for entries selected to show on screen
DATA: BEGIN OF CVIV_VEND_TO_BP1_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE CVIV_VEND_TO_BP1.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_VEND_TO_BP1_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF CVIV_VEND_TO_BP1_TOTAL OCCURS 0010.
INCLUDE STRUCTURE CVIV_VEND_TO_BP1.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_VEND_TO_BP1_TOTAL.

*...processing: CVIV_VEND_TO_BP2................................*
TABLES: CVIV_VEND_TO_BP2, *CVIV_VEND_TO_BP2. "view work areas
CONTROLS: TCTRL_CVIV_VEND_TO_BP2
TYPE TABLEVIEW USING SCREEN '0010'.
DATA: BEGIN OF STATUS_CVIV_VEND_TO_BP2. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_CVIV_VEND_TO_BP2.
* Table for entries selected to show on screen
DATA: BEGIN OF CVIV_VEND_TO_BP2_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE CVIV_VEND_TO_BP2.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_VEND_TO_BP2_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF CVIV_VEND_TO_BP2_TOTAL OCCURS 0010.
INCLUDE STRUCTURE CVIV_VEND_TO_BP2.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF CVIV_VEND_TO_BP2_TOTAL.

*.........table declarations:.................................*
TABLES: CVIC_CCID_LINK                 .
TABLES: CVIC_CP1_LINK                  .
TABLES: CVIC_CP2_LINK                  .
TABLES: CVIC_CP3_LINK                  .
TABLES: CVIC_CP4_LINK                  .
TABLES: CVIC_CUST_TO_BP1               .
TABLES: CVIC_CUST_TO_BP2               .
TABLES: CVIC_LEGFORM_LNK               .
TABLES: CVIC_MAP_CONTACT               .
TABLES: CVIC_MARST_LINK                .
TABLES: CVIC_VEND_TO_BP1               .
TABLES: CVIC_VEND_TO_BP2               .
TABLES: TB019                          .
TABLES: TB020                          .
TABLES: TB027                          .
TABLES: TB027T                         .
TABLES: TB033                          .
TABLES: TB033T                         .
TABLES: TB910                          .
TABLES: TB911                          .
TABLES: TB912                          .
TABLES: TB913                          .
TABLES: TB914                          .
TABLES: TB915                          .
TABLES: TB916                          .
TABLES: TB917                          .
TABLES: TPFK                           .
TABLES: TPFKT                          .
TABLES: TSAB                           .
TABLES: TSABT                          .
TABLES: TVCIN                          .
TABLES: TVCINT                         .
TABLES: TVGF                           .
TABLES: TVGFT                          .
TABLES: TVIP                           .
TABLES: TVIPT                          .
TABLES: TVPV                           .
TABLES: TVPVT                          .
