*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 04.01.2006 at 11:34:22 by user CHANDRASEKAA
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LCVI_VIEW_MAINTTOP.                " Global Data
  INCLUDE LCVI_VIEW_MAINTUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LCVI_VIEW_MAINTF00                      . " subprograms
  INCLUDE LCVI_VIEW_MAINTI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LCVI_VIEW_MAINTF...                " Subprograms
* INCLUDE LCVI_VIEW_MAINTO...                " PBO-Modules
* INCLUDE LCVI_VIEW_MAINTI...                " PAI-Modules
include CVI_MAPPING_CONSTANTs.
INCLUDE LCVI_VIEW_MAINTF01.

INCLUDE LCVI_VIEW_MAINTF02.

INCLUDE LCVI_VIEW_MAINTF03.

INCLUDE LCVI_VIEW_MAINTF04.

INCLUDE LCVI_VIEW_MAINTF05.

INCLUDE LCVI_VIEW_MAINTF06.

INCLUDE LCVI_VIEW_MAINTF07.

INCLUDE LCVI_VIEW_MAINTF08.

INCLUDE LCVI_VIEW_MAINTF09.

INCLUDE LCVI_VIEW_MAINTF10.

INCLUDE LCVI_VIEW_MAINTF11.
