*"* components of interface IF_EX_CVI_MAP_BANKDETAILS
interface IF_EX_CVI_MAP_BANKDETAILS
  public .


  interfaces IF_BADI_INTERFACE .

  methods MAP_BP_BANK_DATA_TO_CUSTOMER
    importing
      !I_PARTNER_GUID type BU_PARTNER_GUID_BAPI
      !I_CUSTOMER_ID type KUNNR
      !I_PARTNER_BANKDETAILS type BUS_EI_BANKDETAIL
    exporting
      !E_CUSTOMER_BANKDETAILS type CVIS_EI_BANKDETAIL
      !E_ERRORS type CVIS_ERROR .
  methods MAP_BP_BANK_DATA_TO_VENDOR
    importing
      !I_PARTNER_GUID type BU_PARTNER_GUID_BAPI
      !I_VENDOR_ID type LIFNR
      !I_PARTNER_BANKDETAILS type BUS_EI_BANKDETAIL
    exporting
      !E_VENDOR_BANKDETAILS type CVIS_EI_BANKDETAIL
      !E_ERRORS type CVIS_ERROR .
  methods MAP_CUSTOMER_BANK_DATA
    importing
      !I_CUSTOMER_ID type KUNNR
      !I_PARTNER_GUID type BU_PARTNER_GUID_BAPI
      !I_CUSTOMER_BANKDETAILS type CVIS_EI_BANKDETAIL
    exporting
      !E_PARTNER_BANKDETAILS type BUS_EI_BANKDETAIL
      !E_ERRORS type CVIS_ERROR .
  methods MAP_VENDOR_BANK_DATA
    importing
      !I_VENDOR_ID type LIFNR
      !I_PARTNER_GUID type BU_PARTNER_GUID_BAPI
      !I_VENDOR_BANKDETAILS type CVIS_EI_BANKDETAIL
    exporting
      !E_PARTNER_BANKDETAILS type BUS_EI_BANKDETAIL
      !E_ERRORS type CVIS_ERROR .
  methods MAP_BP_BANKDETAILS_TO_CUSTOMER
    importing
      !I_PARTNER_GUID type BU_PARTNER_GUID_BAPI
      !I_CUSTOMER_ID type KUNNR
      !I_PARTNER_BANKDETAILS type BUS_EI_BANKDETAIL
    exporting
      !E_CUSTOMER_BANKDETAILS type CVIS_EI_BANKDETAIL
      !E_ERRORS type CVIS_ERROR .
  methods MAP_BP_BANKDETAILS_TO_VENDOR
    importing
      !I_PARTNER_GUID type BU_PARTNER_GUID_BAPI
      !I_VENDOR_ID type LIFNR
      !I_PARTNER_BANKDETAILS type BUS_EI_BANKDETAIL
    exporting
      !E_VENDOR_BANKDETAILS type CVIS_EI_BANKDETAIL
      !E_ERRORS type CVIS_ERROR .
  methods MAP_CUSTOMER_BANKDETAILS
    importing
      !I_CUSTOMER_ID type KUNNR
      !I_PARTNER_GUID type BU_PARTNER_GUID_BAPI
      !I_CUSTOMER_BANKDETAILS type CVIS_EI_BANKDETAIL
    exporting
      !E_PARTNER_BANKDETAILS type BUS_EI_BANKDETAIL
      !E_ERRORS type CVIS_ERROR .
  methods MAP_VENDOR_BANKDETAILS
    importing
      !I_VENDOR_ID type LIFNR
      !I_PARTNER_GUID type BU_PARTNER_GUID_BAPI
      !I_VENDOR_BANKDETAILS type CVIS_EI_BANKDETAIL
    exporting
      !E_PARTNER_BANKDETAILS type BUS_EI_BANKDETAIL
      !E_ERRORS type CVIS_ERROR .
endinterface.
